services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - env/app.env
    ports:
      - "8080:8080"
    networks:
      - shared

  postgres:
    container_name: postgres-sport
    image: postgres:17.5-alpine
    hostname: postgres
    env_file:
      - "./env/postgres.env"
    volumes:
      - pg_data:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - shared

volumes:
  pg_data:

networks:
  shared:
    driver: bridge